// GENERATED by scripts/gen-emojis.ts. Do not edit by hand. (TODO Track A: regenerate)
export interface EmojiEntry { e: string; n: string }
export const EMOJI_GROUPS: { name: string; emojis: EmojiEntry[] }[] = [];
