// Generates src/lib/emojis.generated.ts from unicode-emoji-json's data-by-group.json.
// Run: npm run gen:emojis
//
// Filters to unicode_version <= 15 (renders on current Windows / Android / iOS), drops the
// "Component" group (skin tone / hair style modifiers, not standalone emoji), and maps the
// long Unicode group names to short display labels.

import fs from 'node:fs';
import path from 'node:path';

interface RawEmoji {
  emoji: string;
  name: string;
  slug: string;
  unicode_version: string;
  skin_tone_support: boolean;
}

interface RawGroup {
  name: string;
  slug: string;
  emojis: RawEmoji[];
}

const GROUP_LABELS: Record<string, string> = {
  'Smileys & Emotion': 'Smileys',
  'People & Body': 'People',
  'Animals & Nature': 'Animals',
  'Food & Drink': 'Food',
  'Travel & Places': 'Travel',
  'Activities': 'Activities',
  'Objects': 'Objects',
  'Symbols': 'Symbols',
  'Flags': 'Flags',
  'Component': 'Component',
};

function loadGroups(): RawGroup[] {
  const dataPath = require.resolve('unicode-emoji-json/data-by-group.json');
  const raw = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

  if (Array.isArray(raw)) {
    return raw as RawGroup[];
  }

  // Fallback: object keyed by group name -> array of emoji entries.
  return Object.entries(raw as Record<string, RawEmoji[]>).map(([name, emojis]) => ({
    name,
    slug: name.toLowerCase().replace(/[^a-z0-9]+/g, '_'),
    emojis,
  }));
}

function main() {
  const groups = loadGroups();

  const lines: string[] = [];
  let total = 0;

  for (const group of groups) {
    if (group.name === 'Component') continue;

    const filtered = group.emojis.filter((e) => parseFloat(e.unicode_version) <= 15);
    if (filtered.length === 0) continue;

    const label = GROUP_LABELS[group.name] ?? group.name;
    const entries = filtered
      .map((e) => `    { e: ${JSON.stringify(e.emoji)}, n: ${JSON.stringify(e.name)} },`)
      .join('\n');

    lines.push(`  {\n    name: ${JSON.stringify(label)},\n    emojis: [\n${entries}\n    ],\n  },`);
    total += filtered.length;
  }

  const header = [
    '// GENERATED by scripts/gen-emojis.ts. Do not edit by hand.',
    '// Run `npm run gen:emojis` to regenerate.',
    '',
    'export interface EmojiEntry {',
    '  e: string;',
    '  n: string;',
    '}',
    '',
    'export const EMOJI_GROUPS: { name: string; emojis: EmojiEntry[] }[] = [',
  ].join('\n');

  const footer = '];\n';

  const out = `${header}\n${lines.join('\n')}\n${footer}`;

  const outPath = path.join(__dirname, '..', 'src', 'lib', 'emojis.generated.ts');
  fs.writeFileSync(outPath, out, 'utf8');

  console.log(`Wrote ${total} emojis across ${lines.length} groups to ${outPath}`);
}

main();
